### ISSUE TITLE
roles is failling on ansible_system_vendor != Dell

### ISSUE THREAD

**Issue by roumano** [ipr-cnrs/openmanage#4]
As you have a tested `ansible_system_vendor is search("Dell") and (ansible_virtualization_role == "host")`

I was thinking to add this Roles on all machines (even on virtualized machine) and the roles will skip if it's not needed.
But it's failling due to this tasks:
```
openmanage : Ensure to remove OpenManage related packages if requested
fatal: [ns4]: FAILED! => {"attempts": 3, "changed": false, "msg": "No package(s) matching 'srvadmin*' available"}
```

My workarround is to add a when condition on the roles side (, but it will be better without this workaround) : 
```
  roles:
  - role: ipr.openmanage
    when:
      - ansible_virtualization_role == "host"
      - ansible_system_vendor is search("Dell")
```
